# Generated by Django 3.0.6 on 2020-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['file']},
        ),
        migrations.AlterField(
            model_name='statement',
            name='file',
            field=models.FileField(upload_to='polls/images'),
        ),
    ]
